[IOI] 2주차 Wootube 기능 구현
woowacourse/miniprojects-2019 pull request #17
Opened 2019-08-21 11:46 UTC by hyojaekim

공통
* 관계 맵핑 적용

User
* [백엔드] 유저 이메일 인증

Video
* [백엔드] 삭제 비동기 구현
* [프론트엔드] 마이페이지에서 영상 목록 조회

Comment
* [백엔드] 댓글 테스트 추가
* [백엔드] 답글 테스트 추가
* [프론트엔드] 댓글 프론트 버그 수정

2019-08-22 08:04 UTC, wmakerjun requested changes
DOM api도 매우 잘 사용하고 있고, 자바스크립트 코드 또한 구조적으로 깔끔하게 구현하고 있는 점이 인상적입니다 💯 
몇가지 개선사항을 남겼으니 참고해주세요 😉

2019-08-22 08:04 UTC, wmakerjun commented on src/main/resources/templates/mypage.html
>      document.querySelector(".side-nav-toggle").addEventListener("click", sideNavToggle);
index.html에 똑같은 로직이 있어요~ 중복을 제거하고 재사용하면 좋을 것 같아요 :)

2019-08-22 08:04 UTC, wmakerjun commented on src/main/resources/templates/mypage.html
> +<script th:inline="javascript">
이번 PR에서 노출되는 코드에 남길 수 없어 이곳에 추가적으로 피드백 남깁니다 :)

https://github.com/woowacourse/miniprojects-2019/blob/8c8fabcb09409b1cec6dedf9e1504ccd1d4fab91/src/main/resources/templates/mypage.html#L164-L175

private 형태로 속성을 만들고 싶은 경우 [vue style guide](https://kr.vuejs.org/v2/style-guide/index.html#Private-%EC%86%8D%EC%84%B1-%EC%9D%B4%EB%A6%84-%ED%95%84%EC%88%98)를 참고해서 적용하면 좋을 것 같아요 :)

2019-08-22 08:04 UTC, wmakerjun commented on src/main/resources/static/js/comment.js
>                      <button class="btn comment-btn edit comment-update-btn">수정</button>
template을 따로 template.js파일을 만들어 관리한다면 어떨까요~?

2019-08-22 08:04 UTC, wmakerjun commented on src/main/resources/static/js/mypage.js
> +    fetch('/api/videos/' + id, new deleteHeaderData())
fetch api를 여러군데서 이용하는데요. 매번 코드에 fetch api를 쓰기보다는 api만 다루는 js파일을 따로 만들어 보면 어떨까요? ajax를 나중에 다른 라이브러리로 이용할 수도 있고, 한 곳에서 관리는 것이 유지 보수 측면에서도 좋을 것 같아 보여요 :)

그리고 url 입력하는 부분을 `/api/videos/${id}`와 같이 [문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 활용한다면 더욱 깔끔해질 것 같아요 :)

2019-08-22 08:04 UTC, eastjun commented on src/main/resources/static/js/mypage.js
> +function deleteHeaderData() {
일반적으로 자바스크립트에서 함수가 일반적인 함수인지 객체를 만들기 위한 목적의 생성자 함수인지 구분하기 위해, 생성자 함수의 첫 문자는 대문자로 표기하는 것이 관례입니다.
ex)
```javascript
function Person(name,email){
    this.name = name;
    this.email = email;
}
```

그런데 deleteHeaderData 함수의 경우 똑같은 형태로 반복 사용하는 것인데 13라인에처럼 new로 매번 인스턴스를 생성해서 사용해야할 이유가 있을까요~?

2019-08-22 12:17 UTC, MrKwon commented on src/main/resources/templates/mypage.html
> +<script th:inline="javascript">
이렇게 새로운 것도 알게 되네요..😂감사합니다 ! EASTJUN !

2019-08-22 13:26 UTC, woowahan-pjs requested changes
VALUE OBJECT로 대신할 수 있는 DTO가 보입니다.
도메인 패키지에서 의미가 있는 클래스를 더 도출해서 성숙한 소프트웨어를 만들어 보세요.
객체 지향 생활 체조 원칙을 최대한 적용해 보세요.

2019-08-22 13:26 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/domain/model/BaseEntity.java
> +    protected Boolean isActive = true;
`isActive`라는 변수 이름에 대해서 이야기하고 싶네요.
https://stackoverflow.com/questions/5322648/for-a-boolean-field-what-is-the-naming-convention-for-its-getter-setter

2019-08-22 13:26 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/domain/model/BaseEntity.java
> +    protected Boolean isActive = true;
정말 필요한 부분 외에는 참조 자료형 대신 기본 자료형을 사용하면 어떨까요? 아래의 글을 참고하세요.
https://jaehun2841.github.io/2019/03/01/effective-jave-item61

2019-08-22 13:26 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/domain/model/BaseEntity.java
> +    public void softDelete() {
`softDelete()`라는 메서드가 있으면 `hardDelete()`가 있겠죠? 그게 아니라면 `delete()`라는 메서드 이름이 적절할 수 있습니다. 아래의 영상을 함께 보세요.
https://youtu.be/MDZ8wUi-jzU

2019-08-22 13:26 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/web/argument/RedirectionArgumentResolver.java
>  public class RedirectionArgumentResolver implements HandlerMethodArgumentResolver {
분명 어딘가에 "Referer"를 상수로 관리하는 클래스가 있을 거예요. 적극적으로 찾아보세요!

2019-08-22 13:26 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/web/controller/VideoController.java
>          return "redirect:/videos/" + videoResponseDto.getId();
`RedirectView`를 사용할 것인지, `redirect:`를 사용할 것인지 통일하는 것이 좋겠어요.

2019-08-22 13:26 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/web/controller/api/CommentApiController.java
> +    public ResponseEntity createComment(@PathVariable Long videoId, @RequestBody CommentRequestDto commentRequestDto) {
ResponseEntity의 제네릭 타입을 명시하지 않은 이유가 있나요?

2019-08-22 13:26 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/web/controller/api/VideoApiController.java
> +//        UserSession userSession = userSessionManager.getUserSession();
주석 제거!

2019-08-22 13:26 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/domain/model/Comment.java
>          Comment comment = new Comment();
인스턴스 생성 방식이 독특하네요. 기본 생성자를 사용하는 이유가 있을까요?

2019-08-22 13:26 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/domain/model/User.java
> +        if(this.isActive) {
IntelliJ IDEA의 코드 자동 정렬 기능(⌥⌘L, Ctrl+Alt+L)을 사용하면 더 깔끔한 코드를 볼 수 있을 거예요.

2019-08-22 13:26 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/service/VerifyKeyService.java
> +public class VerifyKeyService {
`VerifyKeyService`에 대한 테스트 코드가 필요해 보여요.

2019-08-22 13:26 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/web/controller/api/VideoApiController.java
> +    private static final Logger log = LoggerFactory.getLogger(VideoApiController.class);
`LoggerFactory`와 `@Slf4j` 중 어느 것을 사용할 건가요?

2019-08-22 15:14 UTC, phs1116 requested changes
안녕하세요.
리뷰어 화투입니다 
조금씩 프로젝트게 진행되는게 눈에 띄네요 :+1: 
다만 빈이나 값 주입 방식이 서비스마다 달라서 전체적으로 팀에서 맞추도록 노력해보면 좋을 것 같아요 
몇가지 피드백 추가했는데 참고 부탁드릴게요. :)

2019-08-22 15:14 UTC, phs1116 commented on src/main/java/com/wootube/ioi/domain/model/VerifyKey.java
> +	public VerifyKey(String inActiveUserEmail, String key) {
코드 자동포매팅 적용해주세요! 
인덴트가 안맞네요 :)

2019-08-22 15:14 UTC, phs1116 commented on src/main/java/com/wootube/ioi/domain/model/Video.java
> +        if (!userId.equals(writer.getId())) {
이 메서드에서 한 것과 마찬가지로  getter가 아닌 writer에 메시지를 보내 처리할 수 있을것같아요.

2019-08-22 15:14 UTC, phs1116 commented on src/main/java/com/wootube/ioi/domain/model/Video.java
> +        return this;
matchWriter 매치 여부를 체크하는 메서드인데 this를 돌려주네요.
이유가 있을까요?

2019-08-22 15:14 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/util/S3FileUploader.java
> +    private String bucket;
bucket에 대해서도 마찬가지로 final로 선언하고 대해서도 생성자를 통해 주입 받아보면 어떨까요?

2019-08-22 15:14 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/util/S3FileUploader.java
> +    final AmazonS3 amazonS3Client;
`@Qualifier(value = "amazonS3Client")`도 생성자에서 전달 받을 수 있습니다. :)

2019-08-22 15:14 UTC, phs1116 commented on src/main/java/com/wootube/ioi/web/controller/UserController.java
> +        if (userSession.getId() != null) {
사소하지만 Objects라는 클래스에 자바에서 제공하는 기본 유틸 메서드들이 많은데요. 참고해보세요. :)

2019-08-22 15:14 UTC, phs1116 commented on src/main/java/com/wootube/ioi/web/controller/UserController.java
> +        if (userSession.getId() != null) {
userSession의 ID가 null인 케이스가 있나요? 이 경우에 예외가 아니라 정상 처리가 되는게 맞나요?

2019-08-22 15:14 UTC, phs1116 commented on src/test/java/com/wootube/ioi/service/VideoServiceTest.java
> +//		videoService.deleteById(ID, USER_ID);
사용하지 않은 코드라면 삭제해주세요. :)

2019-08-22 15:14 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/VideoService.java
> +//        Video writerVideo = video.matchWriter(userId);
사용하지 않는 코드라면 삭제해주세요. :)

2019-08-22 15:14 UTC, phs1116 commented on src/main/java/com/wootube/ioi/web/support/JavaMailSenderConfig.java
> +		mailSender.setHost("smtp.gmail.com");
여기 값들도 다 프로퍼티를 통해 주입받는게 낫지 않을까요?

2019-08-22 15:14 UTC, phs1116 commented on src/test/java/com/wootube/ioi/service/VideoServiceTest.java
>  	private ModelMapper modelMapper;
모델매퍼도 Mock일 필요가 있나요???

2019-08-22 15:14 UTC, phs1116 commented on src/test/java/com/wootube/ioi/service/testutil/TestUtil.java
> +    public static final ReplyRequestDto REPLY_REQUEST_DTO1 = ReplyRequestDto.of(REPLY1_CONTENTS);
전역성 클래스인 것 같은데요. 책임에 맞게 필요한 테스트에서 관리하는게 더 낫지않을까 싶네요.

2019-08-22 15:14 UTC, phs1116 commented on src/main/java/com/wootube/ioi/domain/model/Reply.java
> +    public static Reply of(String contents, Comment comment, User writer) {
static factory method가 꼭 필요한건지, 생성자로도 충분하지 않았을까 라는 생각이 드네요.

2019-08-22 15:14 UTC, phs1116 commented on src/main/java/com/wootube/ioi/domain/model/Reply.java
> +    @OnDelete(action = OnDeleteAction.CASCADE)
소프트 딜리트를 사용하는데 해당 속성이 의미가 없어보여요.
혼동을 방지하기 위해 지우는게 좋을 것 같습니다.

2019-08-22 15:14 UTC, phs1116 commented on src/main/java/com/wootube/ioi/domain/model/VerifyKey.java
> +public class VerifyKey {
이 엔티티는 BaseEntity를 사용하지 않는군요??

2019-08-22 15:14 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/EmailService.java
> +	private Environment environment;
다른건 생성자 주입인데 얘만 @Autowired네요. :)

2019-08-23 04:27 UTC, backlo commented on src/main/resources/static/js/mypage.js
> +function deleteHeaderData() {
감사합니다 !

2019-08-23 06:27 UTC, backlo commented on src/main/java/com/wootube/ioi/service/util/S3FileUploader.java
> +    private String bucket;
아 그렇군요 감사합니다! 😄

2019-08-23 06:28 UTC, backlo commented on src/main/java/com/wootube/ioi/service/util/S3FileUploader.java
> +    final AmazonS3 amazonS3Client;
감사합니다^^

2019-08-23 06:31 UTC, backlo commented on src/main/java/com/wootube/ioi/domain/model/Video.java
> +        if (!userId.equals(writer.getId())) {
메세지를 전달하면 되었군요. 피드백 감사합니다! 😃

2019-08-23 06:35 UTC, backlo commented on src/main/java/com/wootube/ioi/domain/model/Video.java
> +        return this;
원래는 video모델에서 사용자와 비디오 만든자가 같지 안은 경우 예외 처리하고 아니면 그대로 video를 보내줄려고 했는데 팀원들과 상의해서 결국 boolean타입으로 변경시켜 예외를 서비스에서 처리 하였습니다.
다시 피드백 부탁드립니다!! 😃

2019-08-23 06:36 UTC, hyojaekim commented on src/main/java/com/wootube/ioi/web/controller/api/CommentApiController.java
> +    public ResponseEntity createComment(@PathVariable Long videoId, @RequestBody CommentRequestDto commentRequestDto) {
다시 생각해보니 코드를 보지 않으면, 반환하는 값이 어떤 값인지 예상할 수가 없었네요. 

피드백 반영하였습니다!

2019-08-23 06:38 UTC, merged

2019-08-23 06:39 UTC, backlo commented on src/test/java/com/wootube/ioi/service/VideoServiceTest.java
> +//		videoService.deleteById(ID, USER_ID);
삭제했습니다 !

2019-08-23 06:39 UTC, backlo commented on src/main/java/com/wootube/ioi/service/VideoService.java
> +//        Video writerVideo = video.matchWriter(userId);
삭제했습니다 !

2019-08-23 06:42 UTC, backlo commented on src/test/java/com/wootube/ioi/service/VideoServiceTest.java
>  	private ModelMapper modelMapper;
VideoService에서 ModelMapper를 주입 하고 있어서 사용을 해야해가지고 Mock으로 만들었습니다.
안그러면 에러가 나가지고...
혹시 다른 방법이 있을까요???

2019-08-23 06:58 UTC, hyojaekim commented on src/main/java/com/wootube/ioi/domain/model/Reply.java
> +    @OnDelete(action = OnDeleteAction.CASCADE)
현재 User만 소프트 딜리트를 사용하기로 해서, 그대로 두려고 합니다!

2019-08-24 17:40 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/util/S3FileUploader.java
> +    final AmazonS3 amazonS3Client;
해당 필드의 접근제어자가 package-private인 이유를 알 수 있을까요?
별다른 이유가 없다면 private으로 선언하는게 좋을 것 같습니다. :)

2019-08-24 17:41 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/util/S3FileUploader.java
> +    final AmazonS3 amazonS3Client;
해당 필드의 접근제어자가 package-privaete인데 이유가 있을까요?

2019-08-26 10:42 UTC, yjll1019 commented on src/main/java/com/wootube/ioi/service/EmailService.java
> +	private Environment environment;
네~ 피드백 반영했습니다!

2019-08-26 10:47 UTC, yjll1019 commented on src/main/java/com/wootube/ioi/domain/model/VerifyKey.java
> +public class VerifyKey {
BaseEntity에서 soft delete 를 처리하기 위한 isActive 라는 필드가 있었는데, 해당 필드가 User 에서만 사용되어 User 로 옮겼습니다.
그 후 BaseEntity를 수정하여 해당 클래스도 BaseEntity를 상속받도록 하였습니다.

2019-08-26 11:08 UTC, MrKwon commented on src/main/java/com/wootube/ioi/web/support/JavaMailSenderConfig.java
> +		mailSender.setHost("smtp.gmail.com");
넵 ! 프로퍼티를 통해 주입 받는 것이 좋을 것 같아요. 피드백 반영하였습니다