[찐브로스] 2주차 우테코북 기능 구현
woowacourse/miniprojects-2019 pull request #18
Opened 2019-08-21 12:47 UTC by andole87

- 유저
* 친구 기능
* 유저 페이지
* 유저의 개인 포스트 페이지

- 게시물
* 이미지 업로드 기능
* 좋아요 기능

- 프로젝트
* 설정 프로필 구분 (local, test, deploy)

감사합니다.

2019-08-22 11:14 UTC, wmakerjun requested changes
코멘트 남길게 별로 없을 정도로 너무 멋지게 구현하고 있습니다! html 코드도 layout과 element별로 나누어서 잘 정리하고 있는 것 같아요!!!! 💯💯  자바스크립트도 많은 노력을 들여서 구현한 흔적이 많이 보입니다 ㅎㅎ 그래서 딱 3가지만 코멘트 남겼는데요.
1. 공백 컨벤션
2. 자바스크립트 표현방식 동일화
3. 인스턴스 생성
위 3가지에 대한 것만 다시한번 빠르게 확인해주면 좋을 것 같아요 :)

2019-08-22 11:14 UTC, wmakerjun commented on src/main/resources/static/js/friend-add.js
> +    const sendFriendRequest = (event)=>{
공백 컨벤션을 맞춰주면 좋을 것 같아요 :)
```(event) => { ```

2019-08-22 11:14 UTC, eastjun commented on src/main/resources/static/js/friend-add.js
> +        const api = new AjaxApi();
api를 이용하는 곳들에서 매번 AjaxApi 객체의 인스턴스를 만들고 있는 특별한 이유가 있을까요? 서로 다른 인스턴스를 만들어서 활용할 목적으로 AjaxApi를 쓸 것 같지는 않은데 생성자 형태로 만든 이유가 궁금합니다~! 또 fetch-api.js 파일에서 this.bodyData를 매번 인스턴스를 생성하는 것도 왜 그렇게 진행한 것인지 궁금합니다! 한번 할당된 객체 형태를 재사용하는 방식으로 이용해도 좋을 것 같아요~
[링크](https://heygyun.tistory.com/45)도 같이 참조하면 좋을 것 같습니다 :)

2019-08-22 11:14 UTC, eastjun commented on src/main/resources/static/js/social-feed.js
> +        reader.onload = (function(aImg) {
arrow function과 일반 function 표기법이 혼재되어 있습니다. 여기서도 다른 부분과 동일하게 arrow function으로 맞춰주면 좋을 것 같아요 :)

2019-08-23 02:17 UTC, woowahanCU approved these changes

2019-08-23 05:57 UTC, wmakerjun approved these changes

2019-08-23 06:31 UTC, merged