[일조] SunBook 3주차 기능 구현
woowacourse/miniprojects-2019 pull request #28
Opened 2019-08-28 08:57 UTC by ddu0422

### 3주차 기능 구현
- 대댓글 작성, 조회
- 친구 기능
  - 친구 신청
  - 친구 추가
  - 친구 거절
  - 친구 삭제
- 사용자 검색

### 해야할 일
- 대댓글 좋아요
- 대대댓글 막기
- 마이페이지 게시글

### 도전과제
- 소켓 (메신저)

2019-08-31 08:19 UTC, wmakerjun requested changes
큰객체별로 자바스크립트 파일을 잘 분리한 점이 아주 멋져요 :)
반복적으로 발생하는 실수들 위주로만 피드백 남겼으니 해당 부분 리팩토링 할 때 같이 진행한다면 또 한단계 성장한 코드가 될 것 같습니다. 남은 기간도 화이팅입니다 :)

2019-08-31 08:19 UTC, wmakerjun commented on src/main/resources/static/js/article.js
> +            if (range === '모두 공개') {
string 문자열을 직접 비교하는 것은 나중에 실수나 오류가 발생할 확률을 높이곤 해요~
따로 상태값을 담는 변수를 만들어서 IS_PUBLIC / ONLY_FRIEND / ONLY_ME 와 같은 속성에 string 값을 담아서 비교하는게 더 좋을 것 같아요. 왜냐하면 표현하는 방식이나 문구가 수정되었을 때 해당 문구를 사용하는 모든 곳을 일일히 체크할 필요가 없게 만들기 위함이에요. return 해주는 값도 의미를 명확히 할 수 있게 변수로 표현하면 더 좋을 것 같아요

아래는 예시입니다 :)

```javascript
const RANGE_STATUS = {
	IS_PUBLIC: '모두 공개',
	ONLY_FRIEND: '친구 공개',
	ONLY_ME: '비공개'
}

 if (range === RANGE_STATUS.IS_PUBLIC) {
        return '0';
    } else if (range === RANGE_STATUS.ONLY_FRIEND) {
        return '1';
    } else if (range === RANGE_STATUS.ONLY_ME) {
        return '2';
}
```

2019-08-31 08:19 UTC, wmakerjun commented on src/main/resources/static/js/reaction.js
> +            if (goodBtn.className === 'fa fa-thumbs-o-up font-size-16') {
className 메서드보다는 element.classList.contains( 'someclass' ); 와 같이 contains 메서드를 이용하는게 더 좋아보입니다. className은 return type이 string이기 때문에 다른사람과 협업과정에서 해당 엘리먼트에 class를 추가로 작성하거나 순서가 바뀌는 경우 원치 않은 오류가 발생할 가능성이 있어보여요~ 아래 링크에서 참조해주세요 :)

[className](https://www.w3schools.com/jsref/prop_html_classname.asp)
[contains](https://www.w3schools.com/jsref/prop_element_classlist.asp)

2019-08-31 08:19 UTC, wmakerjun commented on src/main/resources/static/js/reaction.js
> +            } else if (goodBtn.className === 'fa fa-thumbs-up text-info font-size-16') {
className 메서드보다는 element.classList.contains( 'someclass' ); 와 같이 contains 메서드를 이용하는게 더 좋아보입니다. className은 return type이 string이기 때문에 다른사람과 협업과정에서 해당 엘리먼트에 class를 추가로 작성하거나 순서가 바뀌는 경우 원치 않은 오류가 발생할 가능성이 있어보여요~ 아래 링크에서 참조해주세요 :)

[className](https://www.w3schools.com/jsref/prop_html_classname.asp)
[contains](https://www.w3schools.com/jsref/prop_element_classlist.asp)

2019-08-31 08:19 UTC, wmakerjun commented on src/main/resources/static/js/reaction.js
> +                    .setAttribute('class', 'fa fa-thumbs-up text-info font-size-16');
지금과 같은 방식으로 class를 추가하는것도 물론 가능하나 element의 class들을 다루는데는 classList라는 좋은 메서드가 있습니다. ```element.classList.add('test-class')```와 같이 추가할 수 있어요~! class를 다루는 메서드를 제공하는게 있으니 해당 메서드를 이용하는게 더 좋을 것 같아요 :)

2019-08-31 08:19 UTC, wmakerjun commented on src/main/resources/static/js/reaction.js
> +                document.getElementById(`${objectName}-good-btn-icon-${objectId}`)
88, 91라인에서도 똑같은 element를 가져오는것 같은데 하나의 변수에 담아서 재사용한다면 어떨까요?

2019-08-31 08:19 UTC, wmakerjun commented on src/main/resources/static/js/reaction.js
> +            return Api.post(`/api/${objectName}/${objectId}/good`, data)
109, 113, 117 라인에서도 메서드만 다르고 uri는 모두 똑같이 사용하고 있는데요~ 하나의 변수에 담아서 재사용하는건 어떨까요~?

2019-08-31 08:19 UTC, wmakerjun commented on src/main/resources/static/js/users.js
> +            if (relationship === 'NONE') {
string 문자열을 직접 비교하는 것은 나중에 실수나 오류가 발생할 확률을 높이곤 해요~
따로 상태값을 담는 변수를 만들어서 사용하면 더 좋을 것 같아요 :)

```javascript
const RELATIONSHIP_STATUS = {
	NONE: 'NONE',
	ADD: 'ADD'
	...
}
```
그리고 지금 처럼 상수를 비교하는 부분이 많은 경우 성능상 if else 보다는 switch case가 더 좋을 것 같아요 :)

2019-08-31 08:19 UTC, wmakerjun commented on src/main/resources/static/js/users.js
> +            return Api.get('/api/users/' + userId);
url은 [문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-08-31 08:19 UTC, wmakerjun commented on src/main/resources/static/js/article.js
>              const file = files.files[0];
변수 자체를 재할당하는 것이 아니면은 let 보다는 const를 이용하는게 더 좋습니다 :)
https://smilerici.tistory.com/68

2019-08-31 08:19 UTC, wmakerjun commented on src/main/resources/static/js/article.js
>                  let imgExtension = /(\.jpg|\.jpeg|\.png|\.gif)$/i;
변수 자체를 재할당하는 것이 아니면은 let 보다는 const를 이용하는게 더 좋습니다 :)
https://smilerici.tistory.com/68

2019-08-31 08:19 UTC, wmakerjun commented on src/main/resources/static/js/article.js
>                  data: formData,
Api 객체에서는 fetch api를 썼는데 이 부분에서만 특별히 jquery의 ajax를 사용한 이유가 있을까요? 비동기 통신하는 방식을 통일하면 더 좋을 것 같아요~

2019-08-31 08:19 UTC, wmakerjun commented on src/main/resources/static/js/article.js
>                          contents: contents.value,
data에 값을 할당해주는 함수를 따로 만들어서 중복을 제거하면 어떨까요?

2019-08-31 08:19 UTC, wmakerjun commented on src/main/resources/static/js/comment.js
>              if (target.closest('li[data-list="comment-list"]')) {
html에서의 [data](https://developer.mozilla.org/ko/docs/Learn/HTML/Howto/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%86%8D%EC%84%B1_%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0) 속성은 말 그대로 id나 value 값을 가지는 data를 부여하기 위함인데요 . 
```li[data-list]="comment-list"  ``` 는 데이터를 저장한다고 보기 어려울 것 같아요. 그래서 현재는 comment-list라는 값을 가진 data가 아닌 comment-list 라는 class를 가진 parent를 찾는 방식으로 구현하는게 더 좋을 것 같아요.

2019-08-31 08:19 UTC, wmakerjun commented on src/main/resources/static/js/comment.js
> +                const commentList = document.getElementById('comment-sublist-' + commentId);
url은 [문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-08-31 08:19 UTC, wmakerjun commented on src/main/resources/static/js/comment.js
> +                const comment = target.closest('li[data-object="comment"');
html에서의 [data](https://developer.mozilla.org/ko/docs/Learn/HTML/Howto/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%86%8D%EC%84%B1_%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0) 속성은 말 그대로 id나 value 값을 가지는 data를 부여하기 위함인데요 . 
```li[data-object="comment"  ``` 는 데이터를 저장한다고 보기 어려울 것 같아요. 그래서 현재는 comment라는 값을 가진 data가 아닌 comment 라는 class를 가진 parent를 찾는 방식으로 구현하는게 더 좋을 것 같아요.

2019-08-31 08:19 UTC, eastjun commented on src/main/resources/static/js/comment.js
> +                const commentList = commentId === "" ? document.getElementById('comment-list-' + articleId) :
url은 [문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-08-31 08:19 UTC, eastjun commented on src/main/resources/static/js/common.js
> +        let date = new Date(time);
변수 자체를 재할당하는 것이 아니면은 let 보다는 const를 이용하는게 더 좋습니다 :)
https://smilerici.tistory.com/68

2019-08-31 08:19 UTC, eastjun commented on src/main/resources/static/js/friends.js
> +                .then(response => response.json())
48, 49 line 처럼 위치 컨벤션을 맞춰주면 좋을 것 같아요 :)

2019-08-31 08:19 UTC, eastjun commented on src/main/resources/static/js/friends.js
> +            const btnGroup = target.closest('div[data-object="event-btn-group"]');
html에서의 [data](https://developer.mozilla.org/ko/docs/Learn/HTML/Howto/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%86%8D%EC%84%B1_%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0) 속성은 말 그대로 id나 value 값을 가지는 data를 부여하기 위함인데요 . 
```div[data-object="event-btn-group"]"  ``` 는 데이터를 저장한다고 보기 어려울 것 같아요. 그래서 현재는 event-btn-group라는 값을 가진 data가 아닌 event-btn-group 라는 class를 가진 parent를 찾는 방식으로 구현하는게 더 좋을 것 같아요.

2019-08-31 08:19 UTC, eastjun commented on src/main/resources/static/js/header.js
> +                        document.getElementById("user-url").setAttribute("href", '/users/' + json.id);
url은 [문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-08-31 08:19 UTC, eastjun commented on src/main/resources/static/js/reaction.js
> +            if (target.closest('li[data-btn="article-reaction-good-btn"]')) {
html에서의 data 속성은 말 그대로 id나 value 값을 가지는 data를 부여하기 위함인데요 .
li[data-btn="article-reaction-good-btn"]" 는 데이터를 저장한다고 보기 어려울 것 같아요. 그래서 현재는 article-reaction-good-btn라는 값을 가진 data가 아닌 article-reaction-good-btn라는 class를 가진 parent를 찾는 방식으로 구현하는게 더 좋을 것 같아요.

2019-09-01 04:31 UTC, oeeen commented on src/main/resources/static/js/article.js
>                  data: formData,
fetch api로 header의 content-type을 비워줘야 했는데, 그걸 어떻게 하는지 몰라서 jquery ajax를 썼었는데, 찾아보고 이번에 고치게 되었습니다~ 감사합니다 ❤️

2019-09-03 00:59 UTC, gracefulBrown approved these changes
많은 기능들이 구현되었네요 @_@ 수고많으셨습니다. 👍 
이번 리뷰에는 예외처리 관련 피드백이 좀 있는데요
참고하면서 프로젝트 마무리 해보시면 좋을 것 같아요 :)

2019-09-03 00:59 UTC, gracefulBrown commented on src/main/java/com/woowacourse/sunbook/application/service/CommentService.java
> +            return null;
다른 Service에서는 returen을 Optional로 한 부분도 있는데 여기는 null을 리턴하네요 :)
어떤 방법으로 하면 좋을지 고민해보고 통일해보면 어떨까요?

2019-09-03 00:59 UTC, gracefulBrown commented on src/main/java/com/woowacourse/sunbook/application/service/RelationService.java
> +		Relation toRelation = relationRepository.findByFromAndTo(to, from)
from과 to의 관계를 맺어줄 때 relation 2개를 각각 저장해야하나요?

2019-09-03 00:59 UTC, gracefulBrown commented on src/main/java/com/woowacourse/sunbook/presentation/controller/RelationApiController.java
> +    @GetMapping("/friends")
경로가 /api/friends/friends로 될 것 같은데 의도한 부분이 맞나요?

2019-09-03 00:59 UTC, gracefulBrown commented on src/main/java/com/woowacourse/sunbook/domain/reaction/ReactionArticle.java
> +            throw new IllegalReactionException();
사용자가 hasGood을 true로 만들 때 기존에 hasGood이 true인 경우 excpetion이 발생되는데요
사용자가 의도한 행위의 목적은 이루었기때문에 exception을 발생시키지 않고 이미 처리되었다는 메시지와 응답코드를 응답하는건 어떨까요?

2019-09-03 00:59 UTC, gracefulBrown commented on src/main/java/com/woowacourse/sunbook/domain/reaction/ReactionArticle.java
> +        throw new IllegalReactionException();
remove도 마찬가지입니다 :)
의도한 행동은 이미 수행되었고 이미 수행되었다는 응답을 내려주면 어떨까요?
한번 고민해보세요 ^^

2019-09-03 00:59 UTC, gracefulBrown commented on src/main/java/com/woowacourse/sunbook/domain/relation/Relation.java
> +		throw new RelationException("이미 신청했습니다");
Relation 도메인에 client에 노출 될 메시지가 RelationException 별로 다르게 설정되어있는것인가요?
도메인은 exception만 발생 시키고 응답 메시지 결정은 호출한 쪽, 그러니까 비즈니스 레이어나 프리젠테이션 레이어에서 결정하는건 어떨까요?

2019-09-03 00:59 UTC, gracefulBrown commented on src/main/java/com/woowacourse/sunbook/presentation/support/ArticleArgumentResolver.java
> +                throw new RuntimeException(e);
해당 예외를 따로 처리해주는 부분이 있나요?

2019-09-04 00:54 UTC, woowahan-pjs approved these changes
축하합니다! 백엔드 Java 레벨 2의 모든 미션 완료하였어요. 🥇 
나만의 블로그부터 미니 프로젝트까지
수많은 미션을 수행하느라 대단히 고생 많으셨습니다. 💯 
좋은 개발자가 되기 위한 소중한 밑거름이 되었길 바랍니다.
이만 Merge 하겠습니다.

2019-09-04 00:54 UTC, merged