[찐브로스] 3주차 우테코북 기능 구현
woowacourse/miniprojects-2019 pull request #30
Opened 2019-08-28 12:35 UTC by Deocksoo

3주차 코드 구현 사항입니다. 

1. 테스트 코드 리펙토링
 - 인수 테스트 추가
 - 코드 정리

2. 친구 기능 개선
 양방향에서 단방향 매핑으로 변경하고, 서로 친구 요청을 해야 친구가 되도록 수정하였습니다.

3. 게시글 공유 기능 추가

5. 댓글 기능 추가
 - 댓글 추가
 - 댓글 수정
 - 댓글 삭제

2019-08-31 09:16 UTC, wmakerjun requested changes
자바스크립트 코드 너무 깔끔하게 잘짜서 별로 피드백 드릴게 거의 없을 정도에요!!!! 💯💯💯 
지금하던대로 남은 기간 잘 마무리해주시면 좋을 것 같습니다 :)

아주 약간의 피드백 남겼으니 해당 부분 재빨리 리팩토링하시고 다른 부분에 정진해주세요 늘 응원합니다 찐브로스 😄

2019-08-31 09:16 UTC, wmakerjun commented on src/main/resources/static/js/post-edit.js
>          const url = baseUrl + "/posts/" + contents.dataset.postid;
url은 [문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-08-31 09:16 UTC, wmakerjun commented on src/main/resources/static/js/signup.js
>          pwdConfirm.style.background = "#ffd5e3";
자바스크립트에서 style을 지정해줄 순 있지만, 가능하면 class에 style 속성을 지정하고 그 class를 추가하거나 제거하는 방법으로 구현하는게 css와 javascript의 역할을 잘 분리하는 것 같아요. background 칼라로 #ffd5e3를 넣어주는 경우 css 파일에 bg-pink와 같이 클래스명을 만들고 해당 스타일을 부여한다음, 그 클래스를 엘리먼트에 추가하거나 삭제하는 방향으로 구현해보면 어떨까요~?

2019-08-31 09:16 UTC, eastjun commented on src/main/resources/static/js/friend-list.js
> +            Api.delete('/friends-requests/' + requestFriendId)
[문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-08-31 09:16 UTC, eastjun commented on src/main/resources/static/js/friend-list.js
> +        anchor.href = '/posts?author=' + json.id;
[문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-08-31 09:16 UTC, eastjun commented on src/main/resources/static/js/social-feed.js
> +            case '전체 공개':
string 문자열을 직접 비교하는 것은 나중에 실수나 오류가 발생할 확률을 높이곤 해요~
따로 상태값을 담는 변수를 만들어서 IS_PUBLIC / ONLY_FRIEND / ONLY_ME 와 같은 속성에 string 값을 담아서 비교하는게 더 좋을 것 같아요. 왜냐하면 표현하는 방식이나 문구가 수정되었을 때 해당 문구를 사용하는 모든 곳을 일일히 체크할 필요가 없게 만들기 위함이에요. 

아래는 예시입니다 :)

```javascript
const DISPLAY_STARTEGY = {
	IS_PUBLIC: '전체 공개',
	ONLY_FRIEND: '친구만 공개',
	ONLY_ME: '비공개'
}
```

2019-09-01 02:55 UTC, wmakerjun requested changes
너무 피드백 드린 양이 적어서 다시 보는데 공통적으로 function 선언하는 방식이 제각기인 것 같아요~ 
arrow function을 쓸 것인지 말 것인지 기준을 정해서 다같이 통일하면 좋을 것 같습니다 :)

2019-09-01 02:55 UTC, eastjun commented on src/main/resources/static/js/comment.js
> +                    .then(res => res.json())
arrow function과 일반 function 표기법이 혼재되어 있습니다. 기준을 정해서 모두 통일하면 좋을 것 같아요 :)

2019-09-01 02:55 UTC, eastjun commented on src/main/resources/static/js/post-share.js
> +        const url = baseUrl + "/posts/share";
[문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-09-03 06:44 UTC, woowahanCU approved these changes
안녕하세요! 3주간 미션진행하느라 고생많았어요 💯 
몇가지 피드백 남겼으니 확인해보시고 궁금한 점 있으면 DM 남겨주세요~

2019-09-03 06:44 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzinbros/common/config/AppConfig.java
> +                .build();
👍 

method name은 동작을 구체적으로 드러내는 동사를 사용하시는 것이 좋다고 생각합니다.

http://www.mimul.com/pebble/default/2013/05/04/1367639300999.html

2019-09-03 06:44 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzinbros/common/config/upload/UploadFileResolver.java
> +            return uploadToFactory.create(null);
이 메서드에서 발생할 수 있는 exception은 ClassCastException뿐인걸까요?

그리고 create 메서드에 null을 전달하는 것은 어떤 의미인걸까요?
결국 MediaFile eastjun_profile.jpg을 등록시키던데요.
우선 null로 관리하는 것이 좋을지 https://www.slideshare.net/gyumee/null-142590829
그리고 흘러가는 데이터를 기준으로 코드를 파악하게 되는데요. 객체지향적인 코드인건지
default 파일로 저 이미지를 노출하는 것은 적절한지 등등 생각해볼만한 부분이 있는거 같네요

그리고 exception을 흘려보내고 있는 부분에 대해서도 한번 생각할 부분이 있는거 같네요.
https://www.slipp.net/questions/350

2019-09-03 06:44 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzinbros/post/service/PostService.java
> +        posts.addAll(postRepository.findAllByDisplayStrategyAndAuthor(DisplayStrategy.ONLY_ME, loginUser, sort));
🤔
이 메서드만 놓고 봤을때 아래의 기능이 무엇인지 직관적으로 와닿지가 않네요
```java
postRepository.findAllByDisplayStrategy(DisplayStrategy.ALL, sort);
```

2019-09-03 06:44 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzinbros/post/service/PostService.java
> +        if (user.getId() == loginUserId) {
값을 꺼내와서 비교하기보다는 해당 도메인 객체에게 메시지를 전달하도록 작성해보세요.

2019-09-03 06:44 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzinbros/user/domain/User.java
> +        this(name, email, password, new MediaFile("/images/default/eastjun_profile.jpg"));
상수값을 적극적으로 사용하는 것은 어떨까요

2019-09-03 06:44 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzinbros/user/service/FriendService.java
> +        friendRepository.save(new Friend(receiver, sender));
owner_slave 의 관계가 역일 경우엔 다른 친구 관계로 읽히는데요.
이렇게 설계한 이유가 있는걸까요?

2019-09-03 06:44 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzinbros/user/web/controller/FriendController.java
> +        return new ResponseEntity<>(friends, HttpStatus.OK);
```suggestion
        return ResponseEntity.ok(friends);
```

https://www.baeldung.com/java-constructors-vs-static-factory-methods

2019-09-03 06:44 UTC, woowahanCU commented on src/test/java/com/woowacourse/zzinbros/post/domain/repository/PostRepositoryTest.java
> +//    }
주석은 제거해주세요.

2019-09-03 06:44 UTC, woowahanCU commented on src/test/java/com/woowacourse/zzinbros/post/service/PostServiceTest.java
> +        postRequestDto.setContents(DEFAULT_CONTENT);
초기값을 세팅하는 부분에서 중복 코드들이 많은 경향이 있네요. 메서드를 분리하여 이를 해결할 수는 없을까요.

2019-09-03 08:24 UTC, ssosso requested changes
안녕하세요, 리뷰어 쏘쏘입니다:)
피드백드리오니 확인부탁드립니다:)

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/common/domain/BaseEntity.java
> +        return Objects.hash(id);
모든 Entity가 BaseEntity에 구현된 id 기반의 hashCode를 사용해도 문제가 되지 않을까요~?

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/user/dto/ModifyResponseMessage.java
> +    public ModifyResponseMessage(T object, String message) {
of 메서드가 있네요~ 생성자를 private으로 만드는 건 어떻게 생각하시나요~?

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/user/web/controller/LogoutController.java
> +    @PostMapping
Get 이었다가 Post로 바뀐 이유가 있을까요~?

2019-09-03 08:24 UTC, ssosso commented on src/test/java/com/woowacourse/zzinbros/post/domain/repository/PostRepositoryTest.java
> +//}
좋은 테스트인데 왜 주석처리가 되었을까요~?

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/comment/dto/CommentResponseDto.java
> +                        .map(msg -> ": " + msg).orElse("");
Error를 담을 때 사용하는 공통 포맷의 dto가 별도로 필요하지 않을까요~?

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/comment/service/CommentService.java
> +        final User user = userService.findLoggedInUser(session.getDto());
user를 service로 find하지 않고 session에 있는 id로 author 매칭을 할수는 없을까요~?

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/comment/service/CommentService.java
>      private final CommentRepository commentRepository;
베디의 고민 한번 읽어보시면 좋을 것 같아요, https://velog.io/@dpudpu/4
적용하진 않으셔도 됩니다. 이런걸 고민할 수도 있구나, 고민을 해결하는 방식은 어떤게 있을 수 있을까 경험해보시면 좋을 것 같아요:)

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/common/config/upload/UploadToFactory.java
>          if (strategy.equals("s3")) {
"s3", "local" 상수화되면 어떨까요~?
그리고 strategy가 점점 늘어나면 if문이 계속해서 생겨날텐데 더 좋은 방법은 없을까요~?

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/common/config/upload/UploadToLocal.java
> +            return null;
null이 아닌 Optional을 반환하면 어떨까요~?

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/post/domain/DisplayStrategy.java
> +                .findFirst().orElse(ALL);
valueOf 메서드명은 strategy에 해당하는 값이 없으면 값이 없다고 뱉어줘야 할 것 같은 느낌이 드네요;
(자바에 일반적으로 구현된 valueOf 메서드는 exception을 뱉거나 없으면 없음을 알 수 있는 값을 뱉어요)
ALL을 orElse로 준다면 메서드명에서도 이를 조금은 유추가능해야 하지 않을까요~?

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/post/domain/DisplayStrategy.java
> +                .findFirst().orElse(ALL);
그리고 @Enumerated(EnumType.STRING)을 사용하면 ALL, FRIEND, ONLY_ME와 같이 저장되는 것으로 아는데 tableValue를 별도로 저장하고 읽어와서 자동 변환해줄 수 있도록 설정하신 곳이 있을까요~?

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/post/domain/Post.java
> +        this.mediaFiles = mediaFile;
복수형 제거

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/post/domain/SharedPost.java
> +    @ManyToOne
모든 ManyToOne에 LAZY사용 검토 부탁드립니다

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/user/web/support/UserSession.java
getDto에서 새 인스턴스를 만들 때 UserResponseDto에게 copy를 요청하면 어떨까요~?

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/user/web/controller/rest/FriendRequestController.java
> +        UserResponseDto userResponseDto = userSession.getDto();
getDto하지 않고 Session을 그대로 Service에 넘기면 어떨까요~?
(Session 내 별도의 Dto필드가 있는 이유가 무엇인가요~?)

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/user/domain/Friend.java
> +        return new Friend(owner, slave);
of를 만들어두고 new 생성자만 사용하고 있네요, 통일하면 어떨까요~?

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/user/domain/User.java
> +        this(name, email, password, new MediaFile("/images/default/eastjun_profile.jpg"));
MediaFile.generateDefault 와 같은게 있으면 좋겠네요,
MediaFileService에 있는 DEFAULT_URL을 도메인으로 옮겨와서 default MediaFile 인스턴스를 생성해주는 메서드가 있으면 어떨까요~?

2019-09-03 08:24 UTC, ssosso commented on src/main/java/com/woowacourse/zzinbros/user/service/UserService.java
> +            return new UserResponseDto(user.getId(), user.getName(), user.getEmail(), user.getProfile().getUrl());
User를 받아서 Dto를 만들도록 하면 어떨까요~?

2019-09-03 09:05 UTC, yuyu154 commented on src/main/java/com/woowacourse/zzinbros/comment/service/CommentService.java
> +        final User user = userService.findLoggedInUser(session.getDto());
컨트롤러 Layer에서 확인하는 방식으로 수정했습니다!

2019-09-03 09:13 UTC, yuyu154 commented on src/main/resources/static/js/post-share.js
> +        const url = baseUrl + "/posts/share";
백틱을 써서 표현했습니다.  
기존에 이벤트 리스너를 등록하는 부분을 버블링을 통해 수정했습니다.

2019-09-03 09:21 UTC, yuyu154 commented on src/main/java/com/woowacourse/zzinbros/user/domain/Friend.java
> +        return new Friend(owner, slave);
new로 통일했습니다!

2019-09-04 00:55 UTC, woowahan-pjs approved these changes
축하합니다! 백엔드 Java 레벨 2의 모든 미션 완료하였어요. 🥇 
나만의 블로그부터 미니 프로젝트까지
수많은 미션을 수행하느라 대단히 고생 많으셨습니다. 💯 
좋은 개발자가 되기 위한 소중한 밑거름이 되었길 바랍니다.
이만 Merge 하겠습니다.

2019-09-04 00:55 UTC, merged