[IOI] Wootube 3주차 기능 구현
woowacourse/miniprojects-2019 pull request #34
Opened 2019-08-29 08:54 UTC by SEOKHYOENCHOI

안녕하세요. 3주차 구현 기능 목록은 다음과 같습니다.

| | User | Video | Comment | Reply |
|---|---|---|---|---|
|좋아요|  | O | △ | △ |
|조회수| | O | | |
|메인화면 영상 목록|  | O | | |
|마이페이지 영상 목록| O |  | | |
|구독| O | | | |
|프로필 사진| O | | | | 
|정렬| | | O | O | 
|비디오 썸네일| | O | | |

2019-08-30 08:47 UTC, woowahan-pjs requested changes
전체적인 구조가 깔끔하네요. 👍 
아래의 이슈도 얼른 해결하길 바래요!
https://github.com/woowahan-ioi/miniprojects-2019/issues/132

2019-08-30 08:47 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/WootubeApplication.java
> +	public static void main(String[] args) {
탭을 쓸 것인지, 스페이스를 쓸 것인지 통일하는 것이 좋겠죠?

2019-08-30 08:47 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/domain/model/ProfileImage.java
> +    public static final String DEFAULT_PROFILE_IMAGE_URL = "https://woowa-ioi.s3.ap-northeast-2.amazonaws.com/wootube/basic/default_profile.png";
s3 도메인은 프로퍼티로 관리할 수 없을까요?

2019-08-30 08:47 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/domain/repository/SubscriptionRepository.java
> +    Long countBySubscribedUserId(Long userId);
참조 자료형 대신 기본 자료형을 사용하면 어떨까요? 아래의 글을 참고하세요.
https://jaehun2841.github.io/2019/03/01/effective-jave-item61

2019-08-30 08:47 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/domain/repository/VideoRepository.java
> +    List<Video> findTop12ByOrderByViewsDesc();
12와 20의 기준이 있나요? `Pageable`을 사용할 수 없나요?

2019-08-30 08:47 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/domain/repository/VideoRepository.java
> +
공백 라인을 의미 있게 사용하는 것이 좋아 보이며, 문맥을 분리하는 부분에 사용하는 것이 좋아요. 과도한 공백은 다른 개발자에게 의문을 줄 수 있어요.

2019-08-30 08:47 UTC, woowahan-pjs commented on src/main/java/com/wootube/ioi/service/util/FileUploader.java
>  public interface FileUploader {
`FileUploader` 👍

2019-08-31 12:56 UTC, phs1116 requested changes
안녕하세요! 리뷰어 화투입니다.
프로젝트가 슬슬 막바지로 가고있네요. 👍 
몇가지 실수로 빼먹으신 것 같은 부분에 대해서와
의존이 점점 많아지는 부분,
정렬, 페이지네이션 관련해서 피드백 추가했습니다.

참고 부탁드릴게요. :)

2019-08-31 12:56 UTC, phs1116 commented on src/main/java/com/wootube/ioi/domain/model/User.java
> +        if (!this.active) {
이미 삭제된 객체를 다시 삭제한다고 예외를 뿜을 이유가 있을까요?

2019-08-31 12:56 UTC, phs1116 commented on src/main/java/com/wootube/ioi/domain/repository/VideoRepository.java
> +    List<Video> findTop12ByOrderByViewsDesc();
Page 외에 정렬 기준에 추가될 때마다 메서드가 계속 증가 될 것 같은데요.
Pageable과 Sort를 활용해서 동적으로 처리할 수 있는 방법을 고민해보면 좋을것 같아요.

2019-08-31 12:56 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/SubscriptionService.java
> +    public List<SubscriberResponseDto> findAllUsersBySubscriberId(Long subscriberId) {
페이지네이션을 적용하지 않아도 괜찮은 기능인가요?

2019-08-31 12:56 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/UserService.java
> +    public UserService(UserRepository userRepository, EmailService emailService, VerifyKeyService verifyKeyService, ModelMapper modelMapper, FileUploader fileUploader, FileConverter fileConverter) {
의존객체가 상당히 많네요. 
책임을 좀 더 나누어보면 어떨까요?

2019-08-31 12:56 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/VideoLikeService.java
> +		if(existsVideoLike(videoId, userId)) {
if 오른쪽 공백 포매팅 신경써주세요 :) 
이미 존재하는 좋아요가 있을 시 매번 쓸대없이 VideoLike 엔티티를 생성하는 것 같아요.
순서를 바꿔서 조정해보면 좋을 것 같네요. :)

2019-08-31 12:56 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/VideoService.java
> +    public VideoService(FileUploader fileUploader, ModelMapper modelMapper, VideoRepository videoRepository, UserService userService, FileConverter fileConverter) {
마찬가지로 의존 객체가 점점 많아지네요.
조금 더 추상화해서 줄여보면 좋을 것 같아요.

2019-08-31 12:56 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/VideoService.java
> +    public void update(Long id, MultipartFile uploadFile, VideoRequestDto videoRequestDto, Long writerId) throws IOException {
현재 IOException이 발생해도 처리할 수 있는 방법이 없지 않나요?
Uploader나 Converter에서 뱉는다면 언체크드 익셉션으로 전환해서 던져줄 수 있지 않을까요?

2019-08-31 12:56 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/util/FileConverter.java
> +        return Optional.of(imgFile);
두 convert 메서드에 대해서 리턴타입이 옵셔널일 이유가 있나요...??

2019-08-31 12:56 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/util/FileConverter.java
> +    public Optional<File> convert(MultipartFile file) throws IOException {
다른 곳에서는 IOException을 예외전환하는데 여기서는 별 처리가 안되어있네요.

2019-08-31 12:56 UTC, phs1116 commented on src/main/java/com/wootube/ioi/web/controller/api/ReplyApiController.java
> +    @GetMapping("/sort/updatetime")
/sort/updatetime 보다는 Sort 조건을 동적으로 받아 처리하는게 더 유연하지 않을까요?
경로가 리소스를 표현하는 Rest 스펙에도 적합하지 않은 것 같아요.

2019-08-31 12:56 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/VideoService.java
> +    public List<VideoResponseDto> findLatestVideos() {
댓글이나 동영상 리스트에 페이지네이션을 넣는게 좋지 않을까요?

2019-09-01 02:13 UTC, wmakerjun requested changes
컨벤션 말고는 크게 피드백할게 없을 정도로 잘하고 있어요 💯💯 컨벤션 위주로만 리팩토링할 때 참고해주면 좋을 것 같네요 :) 시간이 얼마 남지 않았으니까 남은 시간동안도 화이팅입니다~!!!!  😄

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/comment.js
> +            let target = event.target;
target이 value가 재할당 되지 않는데 let으로 선언한 이유가 있을까요~? 값을 재할당 하는 것이 아니라면, const를 쓰는게 좋습니다 :)

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/comment.js
> +            const requestUri = '/api/videos/' + videoId + '/comments/' + commentId;
url은 [문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/reply.js
> +            const requestUri = '/api/videos/' + videoId + '/comments/' + commentId +'/replies/sort/updatetime';
url은 [문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/reply.js
> +            const requestUri = '/api/videos/' + videoId + '/comments/' + id + '/replies';
url은 [문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/reply.js
> +            const requestUri = '/api/videos/' + videoId + '/comments/' + commentId + '/replies/' + replyId;
url은 [문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/reply.js
> +            let target = event.target;
updateReply 함수에서 target 변수에 값이 재할당 되지 않고 있어요. 값을 재할당 하는 경우가 아니라면 const를 써주는게 좋습니다 :)

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/reply.js
> +            let target = event.target;
deleteReply 함수에서 target 변수에 값이 재할당 되지 않고 있어요. 값을 재할당 하는 경우가 아니라면 const를 써주는게 좋습니다 :)

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/reply.js
> +            if(target.tagName === "I" || target.tagName === "SPAN") {
if 하고 괄호하는 컨벤션이 다른 곳에서는 if () 인데, 몇몇 군데에서는 if()로 공백없이 작성하는게 반복되는 것 같아요~ ctrl+r 버튼으로 손쉽게 찾아 바꾸기가 가능하니 통일하면 좋을 것 같아요 :)

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/video-edit.js
> +    const width = 0;
const로 선언한 변수인 width를  18 line에서 ++을 해주고 있네요 let으로 변경해줘야 할 것 같아요

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/templates/mypage.html
> +                                    >
58 line을 보면 속성을 작성하는 컨벤션을 다르게 가져가는 것 같아요. 
괄호를 닫는 컨벤션도 38line처럼 vuetify 공식문서와 같이 가져가도 좋고, 속성과 함께 닫아도 좋은데 통일시켜주면 더 좋을 것 같아요~!

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/comment.js
> +            const requestUri = '/api/videos/' + videoId + '/comments/sort/updatetime';
[문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/comment.js
> +            const requestUri = '/api/videos/' + videoId + '/comments';
[문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/comment.js
>              const inputComment = event.target.parentElement.parentElement.querySelector("INPUT");
parentElement를 chaining해서 element를 찾는 방식은 나중에 저 depth에 다른 ui 엘리먼트 같은게 추가되면서 에러를 발생시킬 확률을 더 높여줄 수 있어요~ 그래서 parentElement 대신에 [closest](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest)를 활용하는걸 추천합니다 :)

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/comment.js
> +                        let currentCommentCount = parseInt(commentCount.innerText)
변수 자체를 재할당하는 것이 아니면은 let 보다는 const를 이용하는게 더 좋습니다 :)
https://smilerici.tistory.com/68

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/comment.js
> +            const requestUri = '/api/videos/' + videoId + '/comments/' + commentId;
[문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/reply.js
>              document.querySelector("#comment-area").addEventListener("click", replyService.toggleReplyCancel);
document.querySelector("#comment-area")를 한 변수에 담아서 재사용하면 어떨까요~? :)

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/reply.js
> +            const commentId = target.closest("ul").parentElement.parentElement.dataset.commentid;
parentElement를 chaining해서 element를 찾는 방식은 나중에 저 depth에 다른 ui 엘리먼트 같은게 추가되면서 에러를 발생시킬 확률을 더 높여줄 수 있어요~ 그래서 parentElement 대신에 [closest](https://developer.mozilla.org/en-US/docs/Web/API/Element/closest)를 활용하는걸 추천합니다 :)

2019-09-01 02:13 UTC, wmakerjun commented on src/main/resources/static/js/reply.js
> +            const requestUri = '/api/videos/' + videoId + '/comments/' + commentId + '/replies/' + replyId;
[문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-09-01 02:13 UTC, eastjun commented on src/main/resources/static/js/subscribe.js
> +                        if(subscriptionCheck.subscribe) {
if 다음에 괄호 사이에 [공백컨벤션](https://ui.toast.com/fe-guide/ko_CODING-CONVENSION/#%EA%B3%B5%EB%B0%B1)에 맞게 공백을 넣어주세요 :)

2019-09-01 02:13 UTC, eastjun commented on src/main/resources/static/js/subscribe.js
> +            if(event.target.tagName === "SPAN") {
if 다음에 괄호 사이에 [공백컨벤션](https://ui.toast.com/fe-guide/ko_CODING-CONVENSION/#%EA%B3%B5%EB%B0%B1)에 맞게 공백을 넣어주세요 :)

2019-09-01 02:13 UTC, eastjun commented on src/main/resources/static/js/subscribe.js
> +            if(event.target.tagName === "SPAN") {
if 다음에 괄호 사이에 [공백컨벤션](https://ui.toast.com/fe-guide/ko_CODING-CONVENSION/#%EA%B3%B5%EB%B0%B1)에 맞게 공백을 넣어주세요 :)

2019-09-01 02:13 UTC, eastjun commented on src/main/resources/static/js/reply.js
> +            if(!target.classList.contains("reply-update-btn")) {
if 다음에 괄호 사이에 [공백컨벤션](https://ui.toast.com/fe-guide/ko_CODING-CONVENSION/#%EA%B3%B5%EB%B0%B1)에 맞게 공백을 넣어주세요 :)

2019-09-01 02:13 UTC, eastjun commented on src/main/resources/static/js/reply.js
>              if(!event.target.classList.contains("reply-save-btn")) {
if 다음에 괄호 사이에 [공백컨벤션](https://ui.toast.com/fe-guide/ko_CODING-CONVENSION/#%EA%B3%B5%EB%B0%B1)에 맞게 공백을 넣어주세요 :)

2019-09-01 02:13 UTC, eastjun commented on src/main/resources/static/js/templates.js
> +    commentTemplate : (comment, writtenTime) => {return `<li class="comment mrg-btm-30" data-commentid="${comment.id}">
return 부분 줄바꿈 해주면 좋을 것 같아요 :)

2019-09-01 02:13 UTC, eastjun commented on src/main/resources/static/js/templates.js
> +    replyTemplate : (reply, writtenTime) => { return `<li class="reply mrg-btm-30" data-replyid="${reply.id}">
return 부분 줄바꿈 해주면 좋을 것 같아요 :)

2019-09-01 02:13 UTC, eastjun commented on src/main/resources/static/js/video-edit.js
> +    const elem = document.getElementById("progressBar");
다른 element들의 id와 class처럼 네이민 컨벤션은 ```progress-bar```로 바꿔주면 더 좋을 것 같아요!

2019-09-01 02:13 UTC, eastjun commented on src/main/resources/static/js/video.js
>      const readMoreSpan = document.querySelector("#readMoreSpan");
다른 element들의 id와 class처럼 네이민 컨벤션은 ```ead-more-span```로 바꿔주면 더 좋을 것 같아요!

2019-09-01 02:13 UTC, eastjun commented on src/main/resources/static/js/video.js
> +    const requestUri = '/api/videos/' + videoId + '/likes/counts';
[문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-09-01 02:13 UTC, eastjun commented on src/main/resources/static/js/video.js
> +                .then(data => document.querySelector("#likeCount").innerHTML = data.count);
다른 element들의 id와 class처럼 네이민 컨벤션은 ```like-count```로 바꿔주면 더 좋을 것 같아요!

2019-09-01 02:13 UTC, eastjun commented on src/main/resources/static/js/video.js
> +            const requestUri = '/api/videos/' + videoId + '/likes';
[문자열 리터럴](https://poiemaweb.com/es6-template-literals)을 참고해서 표현하면 좋을 것 같아요!

2019-09-02 05:55 UTC, MrKwon commented on src/main/resources/static/js/reply.js
> +            let target = event.target;
재할당하는 과정이 있기 때문에 let 으로 유지하겠습니다 !

2019-09-02 05:56 UTC, hyojaekim commented on src/main/resources/static/js/comment.js
>              const inputComment = event.target.parentElement.parentElement.querySelector("INPUT");
감사합니다!!

2019-09-02 13:24 UTC, yjll1019 commented on src/main/java/com/wootube/ioi/service/VideoService.java
> +    public void update(Long id, MultipartFile uploadFile, VideoRequestDto videoRequestDto, Long writerId) throws IOException {
네 피드백 반영해서 IOException을 처리하도록 수정했습니다~!

2019-09-02 14:40 UTC, yjll1019 commented on src/main/java/com/wootube/ioi/service/util/FileConverter.java
> +    public Optional<File> convert(MultipartFile file) throws IOException {
피드백 반영하여 예외 처리 로직 추가했습니다~

2019-09-03 01:16 UTC, yjll1019 commented on src/main/java/com/wootube/ioi/service/util/FileConverter.java
> +        return Optional.of(imgFile);
피드백 반영했습니다~

2019-09-03 16:12 UTC, phs1116 requested changes
안녕하세요. 리뷰어 화투입니다.
S3에 강결합이 되어있는 부분, 에러로그, 정렬 관련해서 피드백 추가했어요.
참고 부탁드릴게요. :)

2019-09-03 16:12 UTC, phs1116 commented on src/main/java/com/wootube/ioi/domain/model/ProfileImage.java
> +    public static final String DEFAULT_PROFILE_IMAGE_URL = "https://woowa-ioi.s3.ap-northeast-2.amazonaws.com/wootube/basic/default_profile.png";
이부분 확인 부탁드릴게요 :)
그리고 엔티티에 직접 해당 이미지에대한 패스를 상세히 가져갈 경우
S3가 아닌 CDN등 다른 솔루션을 사용했을 때 대응하기가 어려울수있어요.
(데이터도 옮기면서 기존의 모든 데이터들에 대한 URL을 수정해야하니까요.)
그리고 이 경우에는 개발 환경과 프로덕션 환경에 대한 분리가 어려워요.

무조건 상용 환경에 있는 S3를 공통으로 사용되야하니까요.

따라서 파일 경로 정도만 가지고 있고 나머지는 제이슨 말대로 프로파일 기반의 프로퍼티로 관리하는게 좋아보여요.

2019-09-03 16:12 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/EmailService.java
> +    private String hostUrl;
`@Value`도 빈과 마찬가지로 생성자를 통해서 주입받을수 있어요. :)

2019-09-03 16:12 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/VideoService.java
> +            S3UploadFileFactory s3UploadFileFactory = new S3UploadFileFactory(uploadFile, fileConverter, fileUploader).invoke();
Uploader 자체는 S3와 상관없이 추상화가 되어있는데 S3UploadFileFactory자체는 추상화가 되어있지 않네요.
이 경우에는 파일 업로드 방식의 변경에 유연하지 않을 것 같아요.
fileConverter, fileUploader를 가지고 있는 FileService를 활용하고 결과값으로 필요한 데이터를 전달받는게 어떨까요?

2019-09-03 16:12 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/util/FileConverter.java
> +            convertFile.delete();
예외 상황이라면 어떤 사유에 대한 에러인지 에러 로그를 찍는게 좋지 않을까요? (e.getMessage 등)
예외를 먹고 FileConvertException를 던지니 정확히 어떤 사유로 에러가 났는지 파악이 되지 않을 것 같아요.

다른 예외를 잡는 부분 전체 포함해서 확인부탁드릴게요. :)

2019-09-03 16:12 UTC, phs1116 commented on src/main/java/com/wootube/ioi/web/controller/api/CommentApiController.java
> +    public ResponseEntity<List<CommentResponseDto>> sortCommentByUpdateTime(@PathVariable Long videoId) {
RestApi URL 디자인에 맞지 않은 것 같아요.
그리고 새로운 소팅 규칙이 추가될 때마다 컨트롤러를 매번 추가하고
이를 프론트에서 판단해서 다르게 호출해야한다는 불편함도 있고요.
`RequestParam`을 통해 Sorting 규칙을 전달받고, JPA 호출에도 해당 Sort를 전달하여 처리할 수 있지 않을까요?

ex) /api/videos/{videoId}/comments?sort=updateTime,desc 
ex) /api/videos/{videoId}/comments?sort=updateTime&order=desc 등

https://www.logicbig.com/tutorials/spring-framework/spring-data/sorting-and-pagination.html
위 방식, 혹은 위 방식으로 해결하기 힘들다면
전달받은 파라미터에 맞는 Sort를 생성하는 팩토리를 만드는것도 좋을 것 같아요.

2019-09-03 16:12 UTC, phs1116 commented on src/main/java/com/wootube/ioi/service/EmailService.java
> +            throw new SendFailException();
에러로그 신경써주세요 :)

2019-09-04 00:57 UTC, woowahan-pjs approved these changes
축하합니다! 백엔드 Java 레벨 2의 모든 미션 완료하였어요. 🥇 
나만의 블로그부터 미니 프로젝트까지
수많은 미션을 수행하느라 대단히 고생 많으셨습니다. 💯 
좋은 개발자가 되기 위한 소중한 밑거름이 되었길 바랍니다.
이만 Merge 하겠습니다.

2019-09-04 00:57 UTC, merged