[Zzazan] 1주차 zzazanstagram 기능 구현
woowacourse/miniprojects-2019 pull request #4
Opened 2019-08-15 09:19 UTC by wbluke

[구현한 기능 목록]
- 프론트엔드 뷰
- 회원가입
- 로그인
- 게시글 저장
- 게시글 조회

패키지 구조를 어떻게 가져가야 할지 잘 몰라서 많이 고민했습니다. 패키지 구조에 대해서 조언 부탁드려요 :)
리뷰 잘 부탁드립니다-! 감사합니다~

2019-08-16 05:49 UTC, wmakerjun requested changes
전반적으로 HTML5에서 제공하는 기본적인 form validation과 api를 매우 잘 활용하고 있습니다. 한 메서드의 길이도 길지 않고 깔끔하게 잘 구현하고 있어요~!  💯 😄 
앞으로 기능이 추가되면서 자바스크립트 코드가 많아질텐데요~ 코드량이 늘어남에 따라 투두리스트 때 작성한 것처럼 구조화를 진행하면, 여러 크루들이 함께 협업하는데 더 큰 도움이 될 것 같아요.

2019-08-16 05:49 UTC, wmakerjun commented on src/main/resources/templates/signup.html
> +    email.addEventListener("input", function (event) {
event객체를 사용하지 않을꺼면 굳이 파라미터로 넣어주지 않아도 좋을 것 같아요 :)

2019-08-16 05:49 UTC, wmakerjun commented on src/main/resources/templates/signup.html
> +    const form = document.querySelector("#signup-from");
지금 회원가입 버튼 눌렀을 때 이벤트 리스너가 동작되지 않습니다. ```querySelector``` 안에 id tag name을 다시 확인해주세요 ㅠㅠ

2019-08-16 05:49 UTC, eastjun commented on src/main/resources/templates/login.html
> +<script>
사용하지 않는 스크립트 태그는 삭제해주세요 :)

2019-08-16 05:49 UTC, eastjun commented on src/main/resources/templates/login.html
> +                        <div class="card" style="width: 350px; display: inline-block; position: absolute; margin-top: 100px">
html 태그에 스타일을 직접 부여하기보다는 따로 css 파일을 만들어서 분리하면 더 좋을 것 같아요~!

2019-08-16 05:49 UTC, eastjun commented on src/main/resources/templates/index.html
> +            $('.advanced-search').removeClass("active");
이건 저의 실수인데...ㅠㅠ 200 line에 있는 코드와 중복된 제이쿼리 코드이기 때문에 201라인 코드는 삭제해주세요 😭

2019-08-16 05:49 UTC, eastjun commented on src/main/resources/templates/article-edit.html
> +        if (confirm("작성하신 게시물을 취소하고 돌아가시겠습니까?") == true) {
정확한 비교를 위해 == 보다는 ===을 이용하는게 좋습니다.
http://guswnsxodlf.github.io/javascript-equal-operator

2019-08-16 05:49 UTC, eastjun commented on src/main/resources/templates/signup.html
> +    const profile = document.querySelector("#signup-form-profile");
사용하지 않는 변수는 지워주세요 :)

2019-08-16 13:25 UTC, kang-hyungu requested changes
코드 깔끔하게 잘 구현하셨어요 👍 
패키지는 지금 구조로 가도 괜찮을 것 같네요
좀더 분리하자면 controller, (컨트롤러에서 사용하는)dto, member session 같이 표현 계층과 관련있는 패키지는 web으로 옮길 수도 있습니다.
몇 가지 코멘트 남겼으니 참고하시고 궁금한 점 있으면 코멘트 남기시거나 dm 주세요

2019-08-16 13:25 UTC, kang-hyungu commented on src/main/java/com/woowacourse/zzazanstagram/model/article/domain/Article.java
> +    protected Article() {
상속을 허용하는게 아니라면 private 접근제어자를 추천드립니다.

2019-08-16 13:25 UTC, kang-hyungu commented on src/main/java/com/woowacourse/zzazanstagram/model/article/domain/Article.java
> +    public static Article from(final Image image, final Contents contents, final Member author) {
지금은 생성자로 충분해 보이는데 팩토리 메서드를 따로 만든 이유가 있을까요?

2019-08-16 13:25 UTC, kang-hyungu commented on src/main/java/com/woowacourse/zzazanstagram/model/article/domain/vo/Contents.java
> +public class Contents {
Contents를 클래스로 새로 정의할 필요가 있을까요?
Article 클래스에서 String contents 필드로 작성하면 코드가 더 간결해지지 않을까요?

2019-08-16 13:25 UTC, kang-hyungu commented on src/main/java/com/woowacourse/zzazanstagram/model/article/domain/vo/Image.java
> +            HttpURLConnection.setFollowRedirects(false);
이미지가 http가 아닌 ftp에 있다면?
다른 통신 방법을 이용해야된다면 http에 의존하는 이 코드가 문제가 되지 않을까요?

2019-08-16 13:25 UTC, kang-hyungu commented on src/main/java/com/woowacourse/zzazanstagram/model/article/dto/ArticleRequest.java
> +    private String hashTag;
이 필드와 관련된 기능은 추가 예정인거죠? article 클래스에서 아직 관련 기능이 안보이네요 ㅎㅎ;

2019-08-16 13:25 UTC, kang-hyungu commented on src/main/java/com/woowacourse/zzazanstagram/model/article/service/ArticleService.java
> +        List<Article> articles = articleRepository.findAllByOrderByIdDesc();
다음 단계 개발하면서 페이징을 추가해보세요!

2019-08-16 13:25 UTC, kang-hyungu commented on src/main/java/com/woowacourse/zzazanstagram/model/common/BaseEntity.java
> +    public void setId(Long id) {
setter 필요할까요?

2019-08-16 13:25 UTC, kang-hyungu commented on src/main/java/com/woowacourse/zzazanstagram/model/member/domain/vo/Email.java
> +    private String email;
email 어노테이션을 적용하는건 어떨까요?

2019-08-16 13:25 UTC, kang-hyungu commented on src/main/java/com/woowacourse/zzazanstagram/model/member/domain/vo/ProfileImage.java
> +            HttpURLConnection.setFollowRedirects(false);
인프라스트럭처 계층 코드가 있네요

2019-08-16 13:25 UTC, kang-hyungu commented on src/main/java/com/woowacourse/zzazanstagram/model/member/domain/vo/ProfileImage.java
> +    public ProfileImage updateUrl(String url) {
메서드명으로 update가 적절해보이진 않네요
valueOf 같이 불변 객체를 생성하는 의미가 담긴 메서드명을 찾아보는건 어떨까요

2019-08-16 13:25 UTC, kang-hyungu commented on src/main/java/com/woowacourse/zzazanstagram/model/member/exception/MemberException.java
> +public class MemberException extends IllegalArgumentException {
Member와 관련된 모든 오류를 이 예외에서 다 처리하지 말고 좀더 세분화해보는건 어떨까요?
회원 로그인 시도할 때 비밀번호가 틀렸을 때 예외, 회원을 찾을 수 없을 때 발생하는 예외 등등으로 나누면 에러 메시지에 의존하지 않고 어떤 이슈인지 빠르게 파악 가능할거에요

2019-08-16 13:25 UTC, kang-hyungu commented on src/main/java/com/woowacourse/zzazanstagram/model/member/service/MemberService.java
> +    private void checkEnrolledNickName(String nickName) {
boolean existsByNickName(NickName nickName);
이 메서드를 memberRepository에 추가하면 코드가 좀더 간결해질거에요

2019-08-16 13:25 UTC, kang-hyungu commented on src/test/java/com/woowacourse/zzazanstagram/model/article/domain/ArticleTest.java
> +    @ValueSource(strings = {"https://image.shutterstock.com/image-photo/white-transparent-leaf-on-mirror-600w-1029171697.jpg", "https://image.shutterstock.com/image-photo/bright-spring-view-cameo-isl
```suggestion
    @ValueSource(strings = {
            "https://image.shutterstock.com/image-photo/white-transparent-leaf-on-mirror-600w-1029171697.jpg",
            "https://image.shutterstock.com/image-photo/bright-spring-view-cameo-island-600w-1048185397.jpg"
    })
```

2019-08-17 06:42 UTC, dasistHYOJIN commented on src/main/java/com/woowacourse/zzazanstagram/model/article/domain/Article.java
> +    protected Article() {
하이버네이트에서 지연로딩을 구현할 때 엔티티 클래스를 상속해서 프록시 객체를 만든다고 알고 있습니다!
그래서 기본 생성자에 private을 지정해두게 되면 프록시 클래스에서 상속을 받지 못하기 때문에 protected로 두었습니다~

2019-08-17 06:53 UTC, dasistHYOJIN commented on src/main/java/com/woowacourse/zzazanstagram/model/article/domain/vo/Contents.java
> +public class Contents {
Contents를 일급컬렉션으로 빼놓은 이유는 **필드를 일관성 있게 구성하고 싶어서** 였습니다!
만약 어떤 필드는 원시타입으로 관리하고 있는데 다른 필드가 일급컬렉션으로 관리하고 있다면 데이터를 관리할 때 혼란스러울 것이라고 생각했습니다 :D

2019-08-17 06:56 UTC, dasistHYOJIN commented on src/main/java/com/woowacourse/zzazanstagram/model/article/domain/vo/Image.java
> +            HttpURLConnection.setFollowRedirects(false);
이 부분은 저희가 차후에 S3를 사용해서 이미지 파일을 관리할 예정에 있기 때문에 ftp는 고려하지 않았습니다!

하지만 나중에 다른 기능을 구현하는 경우에는 이런 부분도 생각을 해봐야겠네요.
알려주셔서 감사합니다!

2019-08-17 06:57 UTC, dasistHYOJIN commented on src/main/java/com/woowacourse/zzazanstagram/model/article/dto/ArticleRequest.java
> +    private String hashTag;
넵 :-D
도메인 설계는 거시적으로 생각하긴 했는데 한 번에 적용할 수는 없을 것 같아서 선언만 해놓았어요~

2019-08-17 07:00 UTC, dasistHYOJIN commented on src/main/java/com/woowacourse/zzazanstagram/model/common/BaseEntity.java
> +    public void setId(Long id) {
앗 변경했습니다!

2019-08-17 07:37 UTC, woowahanCU approved these changes
테스트코드 깔끔하게 잘 작성하셨네요! 💯 
그리고 이슈도 잘 정리하고 있는 것으로 보이는데요. 
칸반보드를 활용하지 않다보니 현재 진행중인 이슈는 무엇인지 확인하기가 어렵네요 ㅠㅠ 
혹시 Projects 탭을 활용하지 않는 이유가 있을까요?

2019-08-17 07:37 UTC, woowahanCU commented on build.gradle
> +dependencies {
gradlew 로 build 실행시에는 테스트를 skip하고 있어요. 
아래 설정 추가한 이후에 배포해보시겠어요?
```java
test {
    useJUnitPlatform()
}
...
dependencies {
...
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.3.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.3.1'
```java

https://www.baeldung.com/junit-5-gradle

2019-08-17 07:37 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzazanstagram/model/article/domain/Article.java
> +        return image.getUrl();
method name은 동작을 구체적으로 드러내는 동사를 사용하시는 것이 좋다고 생각합니다.

http://www.mimul.com/pebble/default/2013/05/04/1367639300999.html

2019-08-17 07:37 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzazanstagram/model/article/domain/vo/Contents.java
> +public class Contents {
일급컬렉션이요? wrapper class를 말씀하신걸까요?

2019-08-17 07:37 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzazanstagram/model/article/domain/vo/Image.java
> +package com.woowacourse.zzazanstagram.model.article.domain.vo;
model pacakge 하위에 controller, service, domain package가 있군요 🤔

2019-08-17 07:37 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzazanstagram/model/article/domain/vo/Image.java
> +            con.setRequestMethod("HEAD");
Image class에서 URL 리소스의 유효성을 검증하는 것이 좋을까요?
Image model이 HttpURLConnection class와 연관관계를 가지는 것보다 
Image 도메인 모델의 생애주기를 관리하는 repository의 구현체, 혹은 dao 등과 연관관계를 가지는 것은 어떨까요?

2019-08-17 07:37 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzazanstagram/util/SessionKeys.java
> +    public static final String MEMBER = "member";
이 클래스는 왜 Util package에 있는 것일까요?
그리고 Utility Class라면 private 생성자를 사용하길 effective java item4에서 가이드하고 있어요

https://medium.com/@biratkirat/learning-effective-java-item-4-4bc457fc5674

2019-08-17 07:37 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzazanstagram/model/member/controller/LoginController.java
> +    @PostMapping("/login")
RequestMapping을 활용할 수 있겠네요.

2019-08-17 07:37 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzazanstagram/model/member/domain/vo/Name.java
> +    public Name updateName(String name) {
Name class이니, validateName, updatName 등의 Name도 중복이지 않을까요? 🙄

2019-08-17 07:37 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzazanstagram/model/member/domain/vo/ProfileImage.java
> +            con.setRequestMethod("HEAD");
Image class에 있는 로직과 중복이네요..? 🙄

2019-08-17 07:37 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzazanstagram/model/member/service/MemberService.java
> +        checkEnrolledNickName(memberSignupRequest.getNickName());
매번 저장할때마다 조회쿼리가 여러번 발생하겠군요. 🙄

2019-08-17 07:37 UTC, woowahanCU commented on src/test/java/com/woowacourse/zzazanstagram/model/RequestTemplate.java
> +public abstract class RequestTemplate {
👍

2019-08-17 07:37 UTC, woowahanCU commented on src/test/java/com/woowacourse/zzazanstagram/model/article/domain/ArticleTest.java
> +    @ValueSource(strings = {"https://image.shutterstock.com/image-photo/white-transparent-leaf-on-mirror-600w-1029171697.jpg", "https://image.shutterstock.com/image-photo/bright-spring-view-cameo-isl
IDE를 사용하시면 보이는 세로선은 이 margin까지만 코드를 작성하자는 컨벤션같은건데요.
옆으로 코드가 나열되면 가독성이 떨어집니다. 보통은 80 ~ 100이 기본입니다.

https://stackoverflow.com/questions/7756112/what-is-the-optimal-ide-text-editor-print-margin-when-programming

2019-08-17 07:47 UTC, wbluke commented
> 테스트코드 깔끔하게 잘 작성하셨네요! 💯
> 그리고 이슈도 잘 정리하고 있는 것으로 보이는데요.
> 칸반보드를 활용하지 않다보니 현재 진행중인 이슈는 무엇인지 확인하기가 어렵네요 ㅠㅠ
> 혹시 Projects 탭을 활용하지 않는 이유가 있을까요?

앗 내부적으로 ZenHub 사용해서 칸반보드 관리하고 있습니다! :) 기능이 많아서 좋은데 외부에선 보이지 않는다는 단점이 있네요ㅜㅜ

2019-08-17 07:50 UTC, woowahanCU commented on src/main/java/com/woowacourse/zzazanstagram/model/article/domain/vo/Image.java
> +            HttpURLConnection.setFollowRedirects(false);
이 걱정은 안하셔도 되겠네요. 크롬이 이제 ftp 지원을 안한다고 합니다 ㅎㅎ; 그러니 저희도.. 😏

https://www.chromestatus.com/feature/6246151319715840

2019-08-17 09:36 UTC, wbluke commented
> 전반적으로 HTML5에서 제공하는 기본적인 form validation과 api를 매우 잘 활용하고 있습니다. 한 메서드의 길이도 길지 않고 깔끔하게 잘 구현하고 있어요~! 💯 😄
> 앞으로 기능이 추가되면서 자바스크립트 코드가 많아질텐데요~ 코드량이 늘어남에 따라 투두리스트 때 작성한 것처럼 구조화를 진행하면, 여러 크루들이 함께 협업하는데 더 큰 도움이 될 것 같아요.

리뷰 주셔서 감사합니다! 주신 피드백은 모두 적용하였는데 구조화 작업은 아직 자바스크립트 실력이 부족하여 진행하지 못하였습니다ㅠㅠ 공부를 조금 더 하고나서 적용해 보겠습니다...!

2019-08-17 11:48 UTC, kang-hyungu commented on src/main/java/com/woowacourse/zzazanstagram/model/article/domain/Article.java
> +    protected Article() {
아 맞네요 그부분을 제가 놓쳤네요 👍

2019-08-17 11:50 UTC, kang-hyungu commented on src/main/java/com/woowacourse/zzazanstagram/model/article/domain/vo/Contents.java
> +public class Contents {
데이터 관리할 때 어떤 점이 어려울지 잘 모르겠네요;
예시나 좀더 자세한 상황을 알려주실 수 있을까요?

2019-08-17 11:54 UTC, kang-hyungu commented on src/main/java/com/woowacourse/zzazanstagram/model/article/domain/vo/Image.java
> +            HttpURLConnection.setFollowRedirects(false);
ftp는 예시구요, 도메인 코드에서 유효성 체크를 위해 http 통신을 할 필요가 있냐는 의견이에요
표현 계층에서 이미지가 존재하는지 결정해도 충분하지 않나요?
지금 이 유효성 체크는 이미지를 호출하는 외부 서비스가 응답이 없으면 같이 영향을 받습니다.
차라리 프론트에서 이미지를 못 불러오더라도 다른 기능은 동작하도록 하고, 이 객체는 이미지 위치만 전달하는 역할만 해도 충분해보입니다.

2019-08-17 12:04 UTC, kang-hyungu approved these changes
피드백 반영 잘 하셨어요 👍 
몇 가지 추가 코멘트 남긴 건 참고하시고 다음 단계 진행하세요!

2019-08-17 12:04 UTC, kang-hyungu commented on src/main/java/com/woowacourse/zzazanstagram/model/member/exception/MemberException.java
> +public class MemberException extends IllegalArgumentException {
MemberException 세분화 잘 하셨어요 👍 
그런데 MemberException이 IllegalArgumentException를 상속하는게 맞을까요?

2019-08-17 12:48 UTC, woowahanCU reviewed
https://github.com/woowacourse/miniprojects-2019/pull/4/commits/28e8bfb0ff8d501acec7e335b9a23c1b83645de9

어라, 이부분 추가안해줘도 테스트 동작하던가요? 🤔
```java
test {
    useJUnitPlatform()
}
```

2019-08-17 13:26 UTC, JunHoPark93 commented
> [28e8bfb](https://github.com/woowacourse/miniprojects-2019/commit/28e8bfb0ff8d501acec7e335b9a23c1b83645de9)
> 
> 어라, 이부분 추가안해줘도 테스트 동작하던가요? 🤔
> 
> ```java
> test {
>     useJUnitPlatform()
> }
> ```

앗 죄송합니다 빼먹었네요 ㅠ 다시 올려놓겠습니다

2019-08-19 00:37 UTC, wmakerjun approved these changes

2019-08-19 03:04 UTC, dasistHYOJIN commented
굿

2019-08-19 03:05 UTC, hyogenie-v approved these changes
아주 멋있고 아름다운 코드와 구조네요
승인합니다

2019-08-19 03:49 UTC, merged