[EDD] 1주차 wootube 기능 구현
woowacourse/miniprojects-2019 pull request #7
Opened 2019-08-15 13:56 UTC by kimjungmin-developer

안녕하세요! 저희는 wootube를 만들고 있는 EDD(Everyone-Driven-Development)입니다! 우선 1주차 기능구현 pr보냅니다! 잘 부탁드립니다!

wootube 1주차 기능구현 목록:

- 배포환경 구축
- 동영상 저장 API 구현
- 메인페이지 구현
- 최신 동영상 리스트 조회 API 구현
- 메인페이지 연결 API 구현
- 동영상 등록 페이지 구현
- 동영상 상세 페이지 구현
- 동영상 상세 API 구현

2019-08-16 07:30 UTC, wmakerjun requested changes
기능에 따라 자바스크립트 파일들을 분리한게 매우 인상적입니다. 💯 
코멘트 남겨준 것들 약간만 수정해준다면 코드가 더 세련되게 될 것 같아요 너무 수고하셨습니다 😃

2019-08-16 07:30 UTC, wmakerjun commented on frontend/js/common.js
> +    var params = {};
var 대신에 let을 이용해주세요 :)
https://www.daleseo.com/js-var-issues/

2019-08-16 07:30 UTC, wmakerjun commented on frontend/js/mainpage.js
> +    api.get("/api/v1/videos?filter=date&page=0&limit=6")
와우! fetchapi.js를 만들어서 api 객체를 활용한 점이 대단합니다 💯 
여기서 한발자국만 더 나아가서 api객체를 다룬다면 보다 더 세련되게 코드를 짤수도 있을 것 같아요!!!

```javascript
const Api = function () {
        const request = (url, method, body) => {
            const defaultHeader = {'Content-Type': 'application/json; charset=UTF-8'}
            return fetch(url, {
                method: method,
                headers: defaultHeader,
                body: body
            })
        }

        const createUser = (userBasicInfo) => {
            return request('/api/users', 'post', userBasicInfo)
        }

        return {
            createUser: createUser
        }
    }

  ...

  const api = new Api()
  
  api
    .createUser(JSON.stringify(userBasicInfo))
    .then(response => alert("success"))
    .catch(error => alert(error));

```

api 객체에서 도메인별 api에 대해서 각각 이름을 부여한다면 그 api를 사용하는 function에서의 로직이 더 명확하게 보일 것 같아요~!

2019-08-16 07:30 UTC, wmakerjun commented on frontend/video-create.html
> +                                        <label for="form-1-1" class="col-md-2 control-label">YOUTUBE ID</label>
label의 for 속성은 연결되는 form element의 id와 동일해야 합니다. form-1-1 속성은 아래에 있는 input의 'youtube-id'로 통일시켜주세요 :)
https://webdir.tistory.com/319

2019-08-16 07:30 UTC, eastjun commented on frontend/js/video/videocardtemplate.js
> +function calculateDate(responseDate) {
우와 시간표시를 하기 위해 꼼꼼하게 구현한 점 너무 멋집니다 💯 
혹시 시간과 관련된 표시를 위해서 다른 기능을 추가하게 된다면 [momentjs](https://momentjs.com) 라이브러리를 활용하면 더욱 쉽고 빠르게 구현할 수도 있어요~! 참고해주길 바래요 :)

2019-08-16 07:30 UTC, eastjun commented on frontend/js/video/videocardtemplate.js
> +    const vidioCardTemplate = `<div class="col-lg-2 padding-2">
**Vidio**CardTemplate에서 Vidio는 오타겠죠? ㅎㅎ
html template 부분에서도 인덴트를 줘서 관리하는게 구조를 파악하고 수정하는데 더욱 용이하답니다. :)
template 파일로 따로 분리해도 좋구요~!

2019-08-17 05:00 UTC, heebong commented on frontend/js/common.js
> +    var params = {};
변경했습니다. 확인 부탁드립니다!

2019-08-17 05:00 UTC, heebong commented on frontend/js/mainpage.js
> +    api.get("/api/v1/videos?filter=date&page=0&limit=6")
변경했습니다. 확인 부탁드립니다!

2019-08-17 05:01 UTC, heebong commented on frontend/video-create.html
> +                                        <label for="form-1-1" class="col-md-2 control-label">YOUTUBE ID</label>
변경했습니다. 확인 부탁드립니다!

2019-08-17 05:01 UTC, heebong commented on frontend/js/video/videocardtemplate.js
> +function calculateDate(responseDate) {
변경했습니다. 확인 부탁드립니다!

2019-08-17 05:01 UTC, heebong commented on frontend/js/video/videocardtemplate.js
> +    const vidioCardTemplate = `<div class="col-lg-2 padding-2">
변경했습니다. 확인 부탁드립니다!

2019-08-17 11:46 UTC, kang-hyungu requested changes
안녕하세요 edd팀 여러분!
도커를 도입하고 프론트, 백엔드로 소스코드를 구분해서 개발 진행하는게 인상 깊네요 👍 
백엔드에 몇 가지 피드백 남겼으니 참고하세요!
궁금한 점 있으면 언제든 dm 주세요

2019-08-17 11:46 UTC, kang-hyungu commented on backend/Dockerfile
> +RUN mv ./src/main/resources/application-production.yml /usr/src/app/application.yml
application.yml 파일명을 변경하는 방법도 있지만 아래와 같이 스프링 띄울 때 어느 설정 파일을 사용할지 정하는 방법도 있어요
$ java -jar -Dspring.profiles.active=production demo-0.0.1-SNAPSHOT.jar
spring boot active profile이라는 검색어로 구글링해보시면 도움이 될거에요

2019-08-17 11:46 UTC, kang-hyungu commented on backend/build.gradle
> +    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
spring rest docs는 안쓰는 것 같은데... 불필요한 의존 라이브러리는 제거해보아요

2019-08-17 11:46 UTC, kang-hyungu commented on backend/build.gradle
> +    id 'org.asciidoctor.convert' version '1.5.3'
asciidoctor도 쓰는 곳이 보이진 않네요

2019-08-17 11:46 UTC, kang-hyungu commented on backend/src/main/java/com/woowacourse/edd/application/converter/VideoConverter.java
> +@Component
스프링 빈 컨테이너에서 관리할 필요가 있을까요?

2019-08-17 11:46 UTC, kang-hyungu commented on backend/src/main/java/com/woowacourse/edd/application/service/VideoService.java
> +    public VideoResponse save(VideoSaveRequestDto requestDto) {
transaction 어노테이션이 필요해보이네요

2019-08-17 11:46 UTC, kang-hyungu commented on backend/src/main/java/com/woowacourse/edd/application/service/VideoService.java
> +    public List<VideoPreviewResponse> findVideosByDate(int page, int limit) {
1. 메소드명은 ByDate인데 검색 조건은 페이징이네요. 정렬조건이 CreateDate이어서 Date을 붙인 것 같네요
2. PageRequest를 컨트롤러에서 전달 받는게 낫지 않을까요? 다른 정렬조건을 붙이고 싶으면 서비스에 메서드를 새로 추가해야되는 구조네요
3. 응답은 Page<VideoPreviewResponse>로 전달하면 API를 사용하는 클라이언트 입장에서 더 많은 정보를 얻을 수 있지 않을까요? 첫 번째 페이지나 마지막 페이지라는 정보 등등..

2019-08-17 11:46 UTC, kang-hyungu commented on backend/src/main/java/com/woowacourse/edd/application/service/VideoService.java
> +        return foundVideos.getContent().stream()
```suggestion
        return foundVideos.map(videoConverter::toPreviewResponse)
                .getContent();
```

응답을 Page<VideoPreviewResponse>로 변경하면 getContent도 필요없을거에요

2019-08-17 11:46 UTC, kang-hyungu commented on backend/src/main/java/com/woowacourse/edd/domain/Video.java
> +    private YoutubeId youtubeId;
YoutubeId, Title, Contents를 vo로 따로 분리할 필요가 있을까요?
vo로 분리했을 때 장점이 현재는 안보이네요

2019-08-17 11:46 UTC, kang-hyungu commented on backend/src/main/java/com/woowacourse/edd/presentation/controller/VideoController.java
> +        if (DATE.equals(filter)) {
1. 필터면 검색조건일텐데 Date은 정렬조건 아닌가요? 메소드명의 의미가 잘못 전달되겠네요
2. 검색 조건을 추가를 위해 컨트롤러에서 if절로 필터하다보면 검색 조건이 늘어나면서 if 절이 많아지고 서비스 메서드도 계속 추가되겠네요. 검색 조건 정보를 담은 객체를 서비스로 넘겨서 처리하는건 어떨까요? jpa specification라는 기술이 있는데 지금 적용하기엔 과하니 서비스에서 적절히 분기처리하거나 querydsl에서 분기처리하기도 해요. 나름의 방법을 찾아서 코드 복잡도를 제거해보세요

2019-08-17 11:46 UTC, kang-hyungu commented on backend/src/main/java/com/woowacourse/edd/presentation/exceptionhandler/VideoExceptionHandler.java
> +        return ResponseEntity.badRequest()
ErrorResponseException을 상속하는 모든 예외는 http response status code를 bad request로 응답하는게 맞을까요?
상황에 따라 400, 401, 404 등으로 나뉘지 않을까요?

2019-08-17 11:46 UTC, kang-hyungu commented on backend/src/main/resources/application-production.yml
> +      ddl-auto: update
운영은 무조건 none으로 처리하세요
변경된 엔티티를 자동으로 적용하는 설정은 무척 위험합니다. update도 위험합니다. 의도치 않게 운영에 반영됐을 때 변경된 db 스키마를 되돌리기 어려울 수 있습니다.

2019-08-17 11:46 UTC, kang-hyungu commented on backend/src/test/java/com/woowacourse/edd/EddApplicationTests.java
> +@ExtendWith(SpringExtension.class)
AutoConfigureWebTestClient, ExtendWith 둘다 필요없는 어노테이션으로 보이네요

2019-08-17 11:46 UTC, kang-hyungu commented on backend/src/test/java/com/woowacourse/edd/application/service/VideoServiceTest.java
> +        when(videoConverter.toEntity(any())).thenReturn(video);
컨버터는 굳이 mocking할 필요 없지 않나요?

2019-08-17 11:46 UTC, kang-hyungu commented on backend/src/test/java/com/woowacourse/edd/application/service/VideoServiceTest.java
> +        assertThat(service.save(new VideoSaveRequestDto("1234", "title", "contents"))).isEqualTo(videoResponse);
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/15669435/63211203-10bdab00-c12f-11e9-9d29-913c9482d887.png">

2019-08-17 11:46 UTC, kang-hyungu commented on backend/src/test/java/com/woowacourse/edd/application/service/VideoServiceTest.java
> +        assertThat(service.save(new VideoSaveRequestDto("1234", "title", "contents"))).isEqualTo(videoResponse);
스샷 보시면 save 변수와 videoResponse 변수가 가리키는 객체가 동일합니다.
동일한(identity) 객체가 아니라 동등한(equality) 객체인지 테스트해봐야하지 않을까요?

2019-08-17 11:46 UTC, kang-hyungu commented on backend/src/test/java/com/woowacourse/edd/domain/VideoTest.java
> +        assertDoesNotThrow(() -> new Video(new YoutubeId("sadfsadfasdf"), new Title("title"), new Contents("contents")));
vo가 많아지면 테스트 코드 작성도 불편해져요
vo가 특별히 하는 일이 없다면 객체로 잘게 쪼개는게 실무에선 독이 될수도 있어요

2019-08-17 11:46 UTC, kang-hyungu commented on backend/src/test/java/com/woowacourse/edd/presentation/controller/VideoControllerTests.java
> +        webTestClient.post().uri("/v1/videos")
webTestClient를 호출 할 때 중복되는 부분을 제거해보면 어떨까요

2019-08-17 11:46 UTC, kang-hyungu commented on backend/src/test/java/com/woowacourse/edd/presentation/controller/VideoControllerTests.java
> +    private String getFormedDate() {
테스트 코드에 중복되서 나오네요.
중복을 제거하려면 다른 클래스를 추가할 수도 있겠네요

2019-08-17 12:41 UTC, gracefulBrown approved these changes
안녕하세요! 브라운입니다.
프로젝트를 잘 수행해주시고 있군요 👍 
몇가지 참고하면 좋은 부분 코멘트로 남겼으니 확인해보시고 진행해주세요 :)
(참고로 실패하는 테스트가 있는경우 빌드가 되면 안되는 점 반드시 인지해주시면 좋을 것 같아요~)

2019-08-17 12:41 UTC, gracefulBrown commented on backend/src/main/java/com/woowacourse/edd/application/converter/VideoConverter.java
> +    public VideoPreviewResponse toPreviewResponse(Video video) {
중복제거를 시도해보면 좋을 것 같네요 :)

2019-08-17 12:41 UTC, gracefulBrown commented on backend/src/main/java/com/woowacourse/edd/application/response/VideoResponse.java
> +    private final long id;
클래스 변수에 final을 선언한 클래스가 있고 선언하지 않은 클래스가 있는데 의도된 내용인가요?
만약 아니라면 final 사용 관련 컨벤션을 맞춰주는것도 좋을 것 같습니다 :)

2019-08-17 12:41 UTC, gracefulBrown commented on backend/src/main/java/com/woowacourse/edd/domain/Video.java
> +    private Long id;
VideoResponse에는 id의 타입이 long을 사용했는데요 의도된 내용인가요?

2019-08-17 12:41 UTC, gracefulBrown commented on backend/src/main/java/com/woowacourse/edd/presentation/controller/VideoController.java
> +        return ResponseEntity.ok(response);
적절한 http status code 를 고민해보면 좋을 것 같아요 :)

2019-08-17 12:41 UTC, gracefulBrown commented on backend/build.gradle
> +dependencies {
현재 빌드 시 실패하는 테스트가 있는경우에도 배포가 되고 있는데요
테스트가 실패할 경우 빌드는 실패가 되어야 합니다.

빌드나 배포할 때 테스트가 수행되는 지 확인해보셨나요?
혹시 테스트가 수행되지 않는다면 아래의 링크를 참고해서 테스트를 수행해보세요!
https://www.baeldung.com/junit-5-gradle

2019-08-17 16:36 UTC, heebong commented on backend/src/test/java/com/woowacourse/edd/EddApplicationTests.java
> +@ExtendWith(SpringExtension.class)
ControllerTests가 EddApplicationTests를 상속받아서 EddApplicationTests에 해당 어노테이션을 추가했습니다. 지금은 ControllerTests가 하나지만 앞으로 더 늘어날 때를 대비해서 상속받는 형식으로 사용했는데 바꾸는게 좋을까요??

2019-08-18 05:52 UTC, Conatuseus commented on backend/src/main/java/com/woowacourse/edd/application/service/VideoService.java
> +    public List<VideoPreviewResponse> findVideosByDate(int page, int limit) {
프론트에서 간단히 요청해서 가져오도록 하고 싶어서 그렇게 했었어요.
저희가 구현한 방법대로 하면 정렬조건에 따라 많은 메서드가 생기는 걸 느꼈습니다.
해당 메서드는 Pageable을 컨트롤러에 전달받도록 했습니다.

2019-08-18 05:53 UTC, Conatuseus commented on backend/src/main/java/com/woowacourse/edd/application/service/VideoService.java
> +        return foundVideos.getContent().stream()
Page로 변경해서 getcontent 삭제했습니다.

2019-08-18 05:56 UTC, Conatuseus commented on backend/src/main/java/com/woowacourse/edd/presentation/controller/VideoController.java
> +        if (DATE.equals(filter)) {
<< 지금은 Pageable로 변경해서 위 내용이 사라졌습니다. >>

if절을 삭제하기 위해 전략패턴이나 그런 것들을 사용하려고 했지만 service layer에 interface를 생성해서 사용해도 되나 라는 의문이 생겨서 해결하지 못했습니다.
jpa specification은 다음에 기회가 되면 공부해서 이런 상황에 사용해보겠습니다!

2019-08-18 12:41 UTC, wmakerjun approved these changes

2019-08-19 02:00 UTC, kang-hyungu commented on backend/src/test/java/com/woowacourse/edd/EddApplicationTests.java
> +@ExtendWith(SpringExtension.class)
SpringBootTest 어노테이션에 포함된 어노테이션들이라 불필요하다고 생각했어요
AutoConfigureWebTestClient는 따로 추가해야될 수도 있어요

2019-08-19 02:05 UTC, kang-hyungu approved these changes
피드백 반영하느라 고생하셨어요!
머지 처리할게요!

2019-08-19 02:06 UTC, merged